version: "3.4"
services:
  mushr_noetic:
    image: mushr/mushr:${OS_TYPE}
    privileged: true
    volumes:
      - ${WS_PATH}/catkin_ws:/root/catkin_ws # Runtime attach
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
